name: Pre Data list

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.12
    - name: Pre Data List
      run: python3 ./predata.py

    - name: Commit and Push to build Branch
      run: |
        git checkout --orphan build
        cd build && rm -rf *
        cp ../gptlist.json .
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add gptlist.json
        git commit -m "Update Data JSON"
        git push origin build -f
